name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: yarn install

      - name: lint
        run: yarn run lint

      - name: setup
        run: node ./bin/index.js reload

      - name: build
        run: yarn run build
        env:
          NITRO_PRESET: github_pages
          BASE_URL: '/${{ github.event.repository.name }}'

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.output/public'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
